repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: local
    hooks:
      - id: metadock-build
        name: Metadock-build documents
        entry: bash -c "bash .metadock/metadock-build-docs.sh" --
        language: system
