name: metadock build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install package
      run: |
        poetry install
    - name: Run `metadock build` and move docs
      run: |
        poetry run metadock build
        cp .metadock/generated_documents/README.md README.md
    - name: Check for modified files
      id: git-check
      run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'David Sillman'
        git config --global user.email 'david-sillman@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "metadock build README"
        git push
